vich_uploader:
    db_driver: orm

    mappings:
        site_image:
            uri_prefix: /images/packages/
            upload_destination: '%kernel.project_dir%/public/assets/images/packages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
